### ISSUE TITLE
Incorrect datebox reference while using multiple dateboxes

### ISSUE THREAD

**Issue by meta-mahesh-chouhan** [jtsage/jtsage-datebox#423] opened 2018-03-10 10:28 UTC
Hi, I have created two input fields with type='datebox' and  I am using datebox 4.3.1 with jQuery Mobile 1.4.5 and jQuery 3.2.1.
So,it's working fine when i am selecting date for first input field and then for second input field. But as I am choosing date again for first input field. The date is being changed for second input field and also datebox is not being closed.
Please have a look http://jsfiddle.net/D2XEn/25/

**Comment by slavap** [comment] 2018-04-26 02:30
@meta-mahesh-chouhan This problem is caused by incompatibility between jQuery3+ and jQueryMobile, if you downgrade jQuery to 2.2.4 in your fiddle, then everything works just fine.

**Comment by jtsage** [comment] 2018-06-07 17:45
I can't express how much I love closing reports when "it's not my fault" - Thanks @slavap !

**Closed by jtsage** 2018-06-07 17:45 UTC
